version: '3.4'

services:
  api:
    container_name: stream-link-locator-api
    build: .
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - stream-network

  postgres:
    container_name: stream-link-locator-postgres
    image: postgres:13-bullseye
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - stream-network

networks:
  stream-network: {}

volumes:
  postgres_data_local: {}